### ISSUE TITLE
Add information

### ISSUE THREAD

**Issue by rotemps** [rouanw/build-window#10]
First thanks a lot for this awesome project!

I would like to know how can I add some more information to the boxes - We have jenkins parameters we are injecting to the build, and we would like to display them too.
for example our build number <Major>.<Minor>.<BuildNumber>

My second question -  Is there any way I can dynamically show downstream jobs from our main job in jnekins?

Thanks,
Rotem.

**Comment by rouanw** [comment]
Glad you find it useful @rotemps. There's not currently any functionality for showing custom parameters or for dynamically finding builds. You are most welcome to open a pull request if there's some functionality you'd like to add. I suspect that the custom parameters wouldn't be too hard to add and that finding downstream jobs would be a bit more work.
