### ISSUE TITLE
Jenkins Authentication

### ISSUE THREAD

**Issue by Alphaa14** [rouanw/build-window#12]
Hi, 
Is there some way to authenticate on Jenkins?

Regards

**Comment by rouanw** [comment]
Hi @Alphaa14. Thanks for asking 😄 Yes! @samlancia [contributed](https://github.com/rouanw/build-window/commit/d163f3e3c2d14b966aa26395b0b745847b562dd9) this functionality.

I've added a note to the `README`: https://github.com/rouanw/build-window#authentication.
