### ISSUE TITLE
Support for Gitlab CI

### ISSUE THREAD

**Issue by Serverfrog** [rouanw/build-window#14]
As Devops i would like to have a Widget to Monitor my Gitlab CI Pipeline/Builds.

**Comment by rouanw** [comment]
Thanks for opening this issue @Serverfrog. I'm afraid I won't have time to implement this at the moment. Would you be keen to open a Pull Request with the functionality you need? Here are a few resources to get you started:

- [The implementation for Jenkins](https://github.com/rouanw/build-window/blob/0d401c16f1ead69f4abc9cbe180cfc9828f5dff4/jobs/build_health.rb#L111-L131)
- [The tests for Jenkins](https://github.com/rouanw/build-window/blob/0d401c16f1ead69f4abc9cbe180cfc9828f5dff4/spec/jenkins_spec.rb)
- [GitLab Pipeline API](https://docs.gitlab.com/ee/api/pipelines.html)

Let me know if I can help.

**Comment by Serverfrog** [comment]
Im not familiar with ruby (more of a java developer) but i can try. You could then see if its meet your standarts ;) But would is smashing good supported anymore (saw that the last commit was over a year ago)

**Comment by rouanw** [comment]
🤷‍♂ Better than the available Dashing support 😸

**Comment by rouanw** [comment]
Hi @cwbs! Thanks for your interest. I'm not aware of anyone working on this, but I think the feature would be great so feel free to open a PR if it would be useful to you.

**Comment by rouanw** [comment]
I'm going to close this but happy to reopen if someone is interested in working on it. I'm afraid I don't have the time to do so at the moment.
