### ISSUE TITLE
cannot load such file -- /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/gems/bundler-1.11.2/bin/bundle (LoadError)

### ISSUE THREAD

**Issue by marcusphi** [rouanw/build-window#7]
The image builds fine with docker compose, but it exits immediately when it tries to run it. In logs I see this:
```
/usr/local/bin/bundle:22:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/gems/bundler-1.11.2/bin/bundle (LoadError)
	from /usr/local/bin/bundle:22:in `<main>'
```
I also tried to start the image manually with docker run and run the commands manually with same result.

**Comment by etheld** [comment]
RUN gem update --system 2.6.1
RUN gem install bundler

Try add this in the Dockerfile before bundle install

**Comment by rouanw** [comment]
@marcusphi - did @etheld's suggestion work for you?
