### ISSUE TITLE
Ran For, View On, and Last Updated values not coming through

### ISSUE THREAD

**Issue by silvercolt** [rouanw/build-window#9]
The following data is not coming through to the dashboard.

"Ran for"
"View on"
"Last Updated"

[See attached screenshot.](https://drive.google.com/file/d/0B4Ye7fEjwjkoaXd0aVBhTC0zb1k/view?usp=sharing)

Any ideas of why this is happening.  I am using Jenkins.

**Comment by rouanw** [comment]
Hi @silvercolt. That's odd. Would you mind checking out d6de79d601dae97490ad8d1d96eccbfcdfb1a494 and seeing if you still get the issue?

```sh
git checkout d6de79d601dae97490ad8d1d96eccbfcdfb1a494
dashing start
```

**Comment by silvercolt** [comment]
Thank you @rouanw however, I do not see any changes other than the addition of the license reference in the ReadMe file. Was there another change expected to help address the Ran for and View on fields?

**Comment by rouanw** [comment]
Nope, it's an old commit. I was wondering whether d163f3e3c2d14b966aa26395b0b745847b562dd9 introduced any issues, as it related to Jenkins.

**Comment by silvercolt** [comment]
Gotcha, I will give it a try.

**Comment by rouanw** [comment]
@silvercolt any luck?

**Comment by silvercolt** [comment]
@rouanw, thank you for following up - I just tried your suggestion and everything is working as expected now.  The following fields are returning expected values:

"Ran for"
"View on"
"Last Updated"

**Comment by rouanw** [comment]
Thanks @silvercolt. Glad you've got something that's working now. I've upgraded the version of `dashing` used, in the hopes that it may solve your problem (I've been unable to reproduce it). 

Would you mind pulling the latest version and giving it a try please?

**Comment by silvercolt** [comment]
I was already using the latest version of dashing and took the files required for the build-window. I just replaced those build-window files you provided with the ones I was using keeping the dashing files as they were.  I will do a diff between my files and the ones you provided to see what is different
